@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzcxNzE4Nzc4LCJleHAiOjE3NzE3MjIzNzh9.TifyE5v5Rw8ZVN2pFetIDeqIFNLdwvCPhIPBe1ZD9PA
GET http://localhost:3000

### POST /
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "vertessymarton",
    "password": "123123213"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "vertessymarton",
    "password": "123123213"
}

###
GET http://localhost:3000/todos
Authorization: Bearer {{token}}

###y
POST http://localhost:3000/todos
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "task": "Finish the project"
}

###
PUT http://localhost:3000/todos/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "completed": true
}

###
DELETE http://localhost:3000/todos/1
Authorization: Bearer {{token}}